---
- name: "Retrieving Secrets From Secrets Manager"
  hosts: localhost
  connection: local
  vars:
    create_users: "{{ lookup('file', 'roles/user_creation/files/createusers').split('\n') }}"
  roles:
    - user_secrets_retrieval
